[package]
name = "rust-alexa-webservice-verifier"
version = "0.1.0"
authors = ["Cory Forsstrom <cforsstrom18@gmail.com>"]
edition = "2018"

[lib]
name = "verifier"
path = "src/lib.rs"

[[bin]]
name = "test"
path = "src/test.rs"

[dependencies]
base64 ="0.10"
der-parser = "2.1"
failure = "0.1"
ring = "0.16"
reqwest = "0.9"
time = "0.1"
url = "2.0"
x509-parser = "0.5"